// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratorTOCByDir(arg1) {
  return window['go']['toc']['TOC']['GeneratorTOCByDir'](arg1);
}

export function GetTOCFromFile(arg1) {
  return window['go']['toc']['TOC']['GetTOCFromFile'](arg1);
}

export function SaveTOCToFile(arg1, arg2) {
  return window['go']['toc']['TOC']['SaveTOCToFile'](arg1, arg2);
}
