// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {toc} from '../models';

export function GeneratorTOCByDir(arg1:string):Promise<toc.Item>;

export function GetTOCFromFile(arg1:string):Promise<toc.Item>;

export function SaveTOCToFile(arg1:string,arg2:toc.Item):Promise<void>;
